#!/bin/bash

####
#### Patrick Dell precision m4500 F14
####

# old blitz
with_blitz=/usr/local/blitz1
# new blitz
#with_blitz=/usr/local/blitz2

with_fftw3=

with_hdf4=/usr/include/hdf,/usr/lib/hdf 

with_plplot=/usr/include/plplot,/usr/lib

enable_cxx_flags_preset=no

enable_threadsafe_blitz=

CXX=icpc 

CXXFLAGS="-std=c++0x -xSSE4.2 -O3 -restrict -vec-report=2 -no-prec-div -no-ansi-alias"

AR=xiar

echo configuring for jazz2
