#!/bin/bash

####
#### Patrick Dell precision m4500 F14
####

# old blitz
with_blitz=/usr/local/blitz1
# new blitz
#with_blitz=/usr/local/blitz2

with_fftw3=

with_hdf4=/usr/include/hdf,/usr/lib/hdf 

with_plplot=/usr/include/plplot,/usr/lib

enable_cxx_flags_preset=no

enable_threadsafe_blitz=

CXX=icpc

CXXFLAGS="-std=c++0x -xSSE4.2 -O3 -restrict -vec-report=2 -no-prec-div -no-ansi-alias"

AR=xiar

enable_mpi=yes

MPICXX="skin mpicxx -cxx=icpc"

#export CXX=$CXX
#export MPICH_CXX=$CXX
#export MPICH2_MPICXX=$CXX
#export MPICH2_MPICXX_FLAGS="-xSSE4.2 -O3 -ip -restrict -vec-report1 -no-prec-div -no-ansi-alias"


#echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
#echo "!!!Don't forget to set the following environment variables!!!"
#echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
#echo "For Berkeley/C shells"
#echo setenv MPICH2_MPICXX \"$MPICH2_MPICXX\"
#echo setenv MPICH2_MPICXX_FLAGS \"$CXXFLAGS\"
#echo "For Bourne shells"
#echo export MPICH2_MPICXX=\"$MPICH2_MPICXX\"
#echo export MPICH2_MPICXX_FLAGS=\"$CXXFLAGS\"
#echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"


echo configuring for jazz2

